// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.2
// source: api/pointsService.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PointsPageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageParam string `protobuf:"bytes,1,opt,name=pageParam,proto3" json:"pageParam,omitempty"`
	PageSize  int32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Id        int64  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PointsPageRequest) Reset() {
	*x = PointsPageRequest{}
	mi := &file_api_pointsService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointsPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointsPageRequest) ProtoMessage() {}

func (x *PointsPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pointsService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointsPageRequest.ProtoReflect.Descriptor instead.
func (*PointsPageRequest) Descriptor() ([]byte, []int) {
	return file_api_pointsService_proto_rawDescGZIP(), []int{0}
}

func (x *PointsPageRequest) GetPageParam() string {
	if x != nil {
		return x.PageParam
	}
	return ""
}

func (x *PointsPageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PointsPageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PointsPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content       []*Point `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	PageNumber    int32    `protobuf:"varint,2,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize      int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	TotalElements int64    `protobuf:"varint,4,opt,name=totalElements,proto3" json:"totalElements,omitempty"`
	TotalPages    int32    `protobuf:"varint,5,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
}

func (x *PointsPage) Reset() {
	*x = PointsPage{}
	mi := &file_api_pointsService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointsPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointsPage) ProtoMessage() {}

func (x *PointsPage) ProtoReflect() protoreflect.Message {
	mi := &file_api_pointsService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointsPage.ProtoReflect.Descriptor instead.
func (*PointsPage) Descriptor() ([]byte, []int) {
	return file_api_pointsService_proto_rawDescGZIP(), []int{1}
}

func (x *PointsPage) GetContent() []*Point {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PointsPage) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *PointsPage) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PointsPage) GetTotalElements() int64 {
	if x != nil {
		return x.TotalElements
	}
	return 0
}

func (x *PointsPage) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_api_pointsService_proto protoreflect.FileDescriptor

var file_api_pointsService_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x0f,
	0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x5d, 0x0a, 0x11, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xb4,
	0x01, 0x0a, 0x0a, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x50, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x24, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x50, 0x61, 0x67, 0x65, 0x73, 0x32, 0x4d, 0x0a, 0x0d, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x50, 0x61, 0x67, 0x65, 0x12, 0x16, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x50, 0x61, 0x67, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x61, 0x77, 0x65, 0x73, 0x6f, 0x6d, 0x61, 0x33,
	0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_pointsService_proto_rawDescOnce sync.Once
	file_api_pointsService_proto_rawDescData = file_api_pointsService_proto_rawDesc
)

func file_api_pointsService_proto_rawDescGZIP() []byte {
	file_api_pointsService_proto_rawDescOnce.Do(func() {
		file_api_pointsService_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_pointsService_proto_rawDescData)
	})
	return file_api_pointsService_proto_rawDescData
}

var file_api_pointsService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_pointsService_proto_goTypes = []any{
	(*PointsPageRequest)(nil), // 0: api.PointsPageRequest
	(*PointsPage)(nil),        // 1: api.PointsPage
	(*Point)(nil),             // 2: api.Point
}
var file_api_pointsService_proto_depIdxs = []int32{
	2, // 0: api.PointsPage.content:type_name -> api.Point
	0, // 1: api.PointsService.GetUserPointsPage:input_type -> api.PointsPageRequest
	1, // 2: api.PointsService.GetUserPointsPage:output_type -> api.PointsPage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_pointsService_proto_init() }
func file_api_pointsService_proto_init() {
	if File_api_pointsService_proto != nil {
		return
	}
	file_api_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_pointsService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pointsService_proto_goTypes,
		DependencyIndexes: file_api_pointsService_proto_depIdxs,
		MessageInfos:      file_api_pointsService_proto_msgTypes,
	}.Build()
	File_api_pointsService_proto = out.File
	file_api_pointsService_proto_rawDesc = nil
	file_api_pointsService_proto_goTypes = nil
	file_api_pointsService_proto_depIdxs = nil
}
